<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Aflevering 5: forslag til besvarelse</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Opgave_5_med_svar_files/libs/clipboard/clipboard.min.js"></script>
<script src="Opgave_5_med_svar_files/libs/quarto-html/quarto.js"></script>
<script src="Opgave_5_med_svar_files/libs/quarto-html/popper.min.js"></script>
<script src="Opgave_5_med_svar_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Opgave_5_med_svar_files/libs/quarto-html/anchor.min.js"></script>
<link href="Opgave_5_med_svar_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Opgave_5_med_svar_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Opgave_5_med_svar_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Opgave_5_med_svar_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Opgave_5_med_svar_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="css_etc/custom-theme-ilisimatusarfik-doc.css">
</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="Opgave_5_med_svar.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Aflevering 5: forslag til besvarelse</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><em>Følgende er et forslag til besvarelse af den femte ud af de seks obligatoriske afleveringer i faget.</em> <em>Brug det til at sammenligne med dine egne svar og diskutér med dine medstuderende.</em></p>
<section id="opret-et-script" class="level2">
<h2 class="anchored" data-anchor-id="opret-et-script">Opret et script</h2>
<p>Start med at åbne RStudio ved at klikke på dit R-project. Opret dernæst et nyt script og gem det i samme mappe, som dit R-project. Du kan f.eks. kalde scriptet <em>Aflevering_5</em>.</p>
</section>
<section id="data" class="level2">
<h2 class="anchored" data-anchor-id="data">Data</h2>
<p>I denne øvelse skal I arbejde videre med European Social Survey (ESS datasættet). I skal derfor ikke downloade et nyt datasæt.</p>
<ul>
<li>Start med at check, at ESS datasættet ligger i samme mappe som dit R-project.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">getwd</span>() <span class="co"># Denne kommando fortæller dig, hvilken mappe du arbejder i lige nu.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "C:/Users/mmn/Dropbox/Ilisimatusarfik/Undervisningsdokumenter/E24/afleveringer"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"C:/Users/mmn/Dropbox/Ilisimatusarfik/Undervisningsdokumenter/E24/slides/data"</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">"ESS.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>Brug <code>filter()</code> funktionen til at gemme et nyt datasæt, der kun indeholder besvarelser fra DK.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">filter</span>(df, land<span class="sc">==</span><span class="st">"DK"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>I skal arbejde med variablene net_indkomst, koen, udd_aar og ansaettelse_type. Kør nedenstående kode for at udvælge variablene og fjerne observationer med missingværdier (NA):</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">select</span>(net_indkomst, koen, udd_aar, ansaettelse_type) <span class="sc">%&gt;%</span> <span class="fu">na.omit</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="sammenhæng-mellem-køn-og-indkomst" class="level2">
<h2 class="anchored" data-anchor-id="sammenhæng-mellem-køn-og-indkomst">Sammenhæng mellem køn og indkomst</h2>
<p>Over de næste opgaver skal I undersøge sammenhængen mellem køn og indkomst.</p>
<section id="opgave-1-simpel-lineær-regression" class="level3">
<h3 class="anchored" data-anchor-id="opgave-1-simpel-lineær-regression">Opgave 1: simpel lineær regression</h3>
<p><strong>a) Start med at lav en tabel over variablen koen (køn).</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span> <span class="fu">tabyl</span>(koen)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   koen   n   percent
   Mand 617 0.5197978
 Kvinde 570 0.4802022</code></pre>
</div>
</div>
<p><strong>b) Skriv med ord, hvilket måleniveau du mener, at variablen koen bør være på</strong></p>
<p><em>En variabel der måler køn i to kategorier, mand og kvinde, bør have nominelt måleniveau, da det ikke er meningsfuldt at rangordne eller tale om meningsfulde afstande mellem kategorierne. Man kan også beskrive den som en dikotom variabel, da den kun tager to værdier.</em></p>
<p><strong>c) Lav to dummy-variable, en for hver af kategorierne på variablen <em>koen</em></strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="at">mand =</span> <span class="fu">ifelse</span>(koen<span class="sc">==</span><span class="st">"Mand"</span>,<span class="dv">1</span>,<span class="dv">0</span>),</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="at">kvinde =</span> <span class="fu">ifelse</span>(koen<span class="sc">==</span><span class="st">"Kvinde"</span>,<span class="dv">1</span>,<span class="dv">0</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>I skal nu undersøge sammenhængen mellem køn og indkomst med lineær regressionsanalyse.</p>
<p><strong>d) Kig på den nedenståene formel for model 1. Skriv med ord, hvilken variabel der er den afhængige, og hvilken variabel, der er den uafhængige:</strong></p>
<p>Model 1: <span class="math inline">\(indkomst = \alpha+\beta_1*kvinde+\epsilon\)</span></p>
<p><em>Indkomst er den afhængige variabel og “kvinde” er den uafhængige. Den afhængige variabel noteres altid til venstre for lighedstegnet, og de uafhængige til højre.</em></p>
<p><strong>e) Estimér model 1</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(net_indkomst <span class="sc">~</span> kvinde, <span class="at">data =</span> df)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(texreg)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>(texreg<span class="sc">::</span><span class="fu">screenreg</span>(<span class="fu">list</span>(model1), <span class="at">include.ci=</span>F))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
=========================
             Model 1     
-------------------------
(Intercept)  16977.70 ***
              (328.66)   
kvinde       -1802.47 ***
              (474.28)   
-------------------------
R^2              0.01    
Adj. R^2         0.01    
Num. obs.     1187       
=========================
*** p &lt; 0.001; ** p &lt; 0.01; * p &lt; 0.05</code></pre>
</div>
</div>
<p><strong>f) Hvad er fortolkningen af værdien for konstantleddet</strong> <span class="math inline">\(\alpha\)</span><strong>?</strong></p>
<p><em>Konstantleddet alpha / intercept er den forventede værdi på den afhængige variabel indkomst, når alle uafhængige variable er lig 0. Dvs. Intercept beskriver den forventede indkomst for en person, der har 0 på den uafhængige variabel kvinde - med andre ord den forventede indkomst for mænd.</em></p>
<p><strong>g) Hvad er fortolkningen af værdien på parameterestimatet for “kvinde” (</strong><span class="math inline">\(\beta_1\)</span><strong>)?</strong></p>
<p><span class="math inline">\(\beta_1\)</span> <em>beskriver ændringen i den afhængige variabel “Indkomst” for én enhedsændring i den uafhængige variabel “Kvinde”. Dvs. den beskriver den forventede ændring i indkomst, når variablen “kvinde” går fra 0 til 1 - med andre ord, når man går fra værdien “mand” til “kvinde”. Kvinder ser altså ud til gennemsnitligt at have en nettoindkomst på 1802 kroner mindre end mænd.</em></p>
<p><strong>h) Er der en statistisk signifikant sammenhæng mellem køn og indkomst?</strong></p>
<p><em>Vi kan aflæse den statistiske sammenhæng mellem dummyvariablen “kvinde” og “indkomst” ved at kigge på stjernerne ud for parameterestimatet. Tre stjerner ud fra parameterestimatet for</em> <span class="math inline">\(\beta_1\)</span> <em>indikerer, at p-værdien er under 0,001.</em> <em>Den er derfor under vores statistiske grænseværdi på 0,05, hvilket betyder, at der ser ud til at være en statistisk signifikant sammenhæng mellem en køn og indkomst - kvinder ser ud til gennemsnitligt at tjene signifikant mindre end mænd (1802 kroner mindre).</em></p>
<p><br></p>
<p>Nu skal du sætte koefficienterne fra dit resultat ind i formlen for regressionsmodellen for at udregne følgende:</p>
<p><strong>i) Hvad er den forventede indkomst for en mand?</strong></p>
<p><em>Regressionsligningen er givet ved:</em></p>
<p><span class="math inline">\(indkomst = \alpha+\beta_1*kvinde+\epsilon\)</span></p>
<p><em>Den forventede indkomst for en mand er således givet ved:</em></p>
<p><span class="math inline">\(indkomst _{mand}= 16978-1803*0=16978+0=16978\)</span></p>
<p><em>Da mænd tager værdien 0 på den uafhængige dummyvariabel “kvinde”.</em></p>
<p><strong>j) Hvad er den forventede indkomst for en kvinde?</strong></p>
<p><em>Den forventede indkomst for en kvinde er givet ved:</em></p>
<p><span class="math inline">\(indkomst _{kvinde}= 16978-1803*1=16978-1803=15175\)</span></p>
<p><em>Da kvinder tager værdien 1 på den uafhængige dummyvariabel “kvinde”.</em></p>
<p><br></p>
</section>
<section id="opgave-2-multipel-lineær-regression-forlæns-modelsøgning" class="level3">
<h3 class="anchored" data-anchor-id="opgave-2-multipel-lineær-regression-forlæns-modelsøgning">Opgave 2: multipel lineær regression (forlæns modelsøgning)</h3>
<p>I har nu undersøgt sammenhængen mellem køn og indkomst i en simpel regressionsmodel. Nu skal I undersøge, om sammenhængen i virkeligheden kan forklares af andre faktorer.</p>
<p>Nogle påstår, at lønforskellen på mænd og kvinder skyldes, at mænd gennemsnitligt set har mere uddannelse end kvinder. I skal derfor indføre variablen “udd_aar” som kontrolvariabel i jeres regressionsmodel for at teste, om forskellen i indkomst mellem mænd og kvinder kan forklares af, at mænd gennemsnitligt tager flere års uddannelse end kvinder.</p>
<p><strong>a) Variablen “udd_aar” måler, hvor mange års uddannelse respondenterne har. Skriv med ord, hvilket måleniveau du mener, at variablen bør have</strong></p>
<p><em>En variabel der måler antal års uddannelse må være intervalskaleret, da det giver mening at rangordne værdierne og afstanden mellem værdierne er konstante og meningsfulde.</em></p>
<p><br></p>
<p>I skal nu undersøge, om sammenhængen mellem køn og indkomst kan forklares af forskelle i antal års uddannelse med følgende model:<br>
<br>
Model 2: <span class="math inline">\(indkomst = \alpha+\beta_1*kvinde+\beta_2*udd\_aar+\epsilon\)</span></p>
<p><strong>b) Estimér model 2</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(net_indkomst <span class="sc">~</span> kvinde <span class="sc">+</span> udd_aar, <span class="at">data =</span> df)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>(texreg<span class="sc">::</span><span class="fu">screenreg</span>(<span class="fu">list</span>(model1, model2), <span class="at">include.ci=</span>F))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
=======================================
             Model 1       Model 2     
---------------------------------------
(Intercept)  16977.70 ***  11506.14 ***
              (328.66)      (649.18)   
kvinde       -1802.47 ***  -1926.81 ***
              (474.28)      (457.02)   
udd_aar                      398.91 ***
                             (41.32)   
---------------------------------------
R^2              0.01          0.08    
Adj. R^2         0.01          0.08    
Num. obs.     1187          1187       
=======================================
*** p &lt; 0.001; ** p &lt; 0.01; * p &lt; 0.05</code></pre>
</div>
</div>
<p><strong>c) Beskriv med ord, hvad fortolkningen af værdien på konstantleddet</strong> <span class="math inline">\(\alpha\)</span> <strong>er nu</strong></p>
<p><em>Konstantleddet alpha / intercept er den forventede værdi på den afhængige variabel indkomst, når alle uafhængige variable er lig 0. Intercept beskriver altså nu den forventede indkomst for en person, der har 0 på den uafhængige variabel “kvinde” OG på den uafhængige variabel “antal års uddannelse”- med andre ord den forventede indkomst for mænd med 0 års uddannelse.</em></p>
<p><strong>d) Beskriv med ord, hvad fortolkningen af værdien på parameterestimatet</strong> <span class="math inline">\(\beta_2\)</span> <strong>for “udd_aar” er</strong></p>
<p><span class="math inline">\(\beta_2\)</span> <em>beskriver ændringen i den afhængige variabel indkomst for én enhedsændring i den uafhængige variabel “antal års uddannelse”. Dvs. den beskriver den forventede ændring i indkomst, når variablen “antal års uddannelse” stiger med 1 - med andre ord, når man får et års uddannelse mere. Det ser altså ud til, at man gennemsnitligt kan forvente en stigning i netto indkomst på 399 DKK, for hvert års ekstra uddannelse, som man tager.<br>
<br>
Da vi har at gøre med en multipel model nu (mere en én uafhængig variabel) er der dog en ekstra fortolkningsmæssig pointe.</em> <span class="math inline">\(\beta_2\)</span> <em>beskriver ændringen i indkomst, når antal års uddannelse stiger med 1, når værdien på den anden uafhængige variabel “kvinde” holdes konstant. Med andre ord beskriver</em> <span class="math inline">\(\beta_2\)</span> <em>ændringen i indkomst, når antal års uddannelse stiger med 1 og der samtidig kontrolleres for køn. I praksis svarer det til, at vi kigger på “effekten” af et års uddannelse, når vi kun sammenligner mænd med mænd og kvinder med kvinder. På den måde er vi sikre på, at den forskel i indkomst vi observerer, når vi skruer på antal års uddannelse, skyldes uddannelse og ikke underliggende forskelle mellem køn.</em></p>
<p><strong>e) Er der en signifikant sammenhæng mellem antal års uddannelse og indkomst?</strong></p>
<p><em>Vi kan aflæse den statistiske sammenhæng mellem variablen “antal års uddannelse” og “indkomst” ved at kigge på stjernerne for parameterestimatet</em> <span class="math inline">\(\beta_2\)</span> <em>tilhørende variablen “udd_aar”. Tre sterner indikerer en p-værdi &lt; 0,001, hvilket er den under vores statistiske grænseværdi på 0,05. Der ser således ud til at være en statistisk signifikant sammenhæng mellem indkomst og antal års uddannelse, også når der tages højde for køn. Jo flere års uddannelse man har, desto mere ser man ud til at tjene (399 DKK kroner mere for hvert år, i gennemsnit).</em></p>
<p><strong>f) Er der fortsat en signifikant forskel mellem køn og indkomst, selv når der kontrolleres for antal aars uddannelse?</strong></p>
<p><em>Vi kan aflæse den statistiske sammenhæng mellem variablen “kvinde” og “indkomst” ved at kigge på p-værdien for parameterestimatet</em> <span class="math inline">\(\beta_1\)</span> <em>tilhørende variablen “kvinde”. Tre stjerner indikerer en p-værdi &lt; 0,001, hvilket er under vores statistiske grænseværdi på 0,05. Det betyder, at der ser ud til at stadig være en statistisk signifikant sammenhæng mellem indkomst og køn. Kvinder ser faktisk ud til gennemsnitligt at tjene 1927 DKK mindre end mænd, når vi har kontrolleret for forskelle i antal års uddannelse. Vi undervurderede altså forskellen i den forrige model.</em></p>
<p><br></p>
<p>Andre påstår, at lønforskellen på mænd og kvinder skyldes, at mænd har andre typer af ansættelse end kvinder har. I skal derfor indføre variablen “ansaettelse_type” som endnu en kontrolvariabel i jeres regressionsmodel for at teste, om sammenhængen mellem køn og indkomst kan forklares af forskelle i <em>ansættelsestyper</em>.</p>
<p><strong>g) Lav en tabel over variablen “ansættelses_type” for at undersøge, hvilke ansættelsestyper variablen indeholder.<br>
</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tabyl</span>(df<span class="sc">$</span>ansaettelse_type)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> df$ansaettelse_type    n    percent
         Lønmodtager 1129 0.95113732
         Selvstændig   54 0.04549284
             Familie    4 0.00336984</code></pre>
</div>
</div>
<p><em>Tabellen viser, at vi har tre kategorier “lønmodtager”, “selvstændig”, og “familie” (hjemmegående). Der er dog kun 4 observationer i kategorien “familie”. Dette gør den i princippet uegnet til statistisk analyse. Når vi har meget små antal observationer ved vi, at den statistiske usikkerhed bliver meget stor. I dette tilfælde indkluderer vi den dog for eksemplets skyld.</em></p>
<p><strong>h) Skriv med ord, hvilket måleniveau du mener, at variablen ansaettelse_type bør være på<br>
<em>dit svar</em></strong></p>
<p><em>En variabel der måler ansættelsestyper såsom “lønmodtager”, “selvstændig”, og “familie” må være nominal, da kategorierne ikke kan rangordnes. Der er heller ikke meningsfuld afstand mellem dem.</em></p>
<p><strong>i) Lav tre dummy variable, en for hver kategori på variablen ansaettelse_type</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">loenmodtager =</span> <span class="fu">ifelse</span>(ansaettelse_type<span class="sc">==</span><span class="st">"Lønmodtager"</span>,<span class="dv">1</span>,<span class="dv">0</span>),</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">selvstaending =</span> <span class="fu">ifelse</span>(ansaettelse_type<span class="sc">==</span><span class="st">"Selvstændig"</span>,<span class="dv">1</span>,<span class="dv">0</span>),</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">familie =</span> <span class="fu">ifelse</span>(ansaettelse_type<span class="sc">==</span><span class="st">"Familie"</span>,<span class="dv">1</span>,<span class="dv">0</span>)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>I skal nu undersøge om sammenhængen mellem køn og indkomst kan forklares af antal års uddannelse eller ansættelsestype. Kig på formlen nedenfor for model 3.<br>
<br>
Model 3: <span class="math inline">\(indkomst = \alpha+\beta_1*kvinde+\beta_2*udd\_aar+\beta_3*selvstændig+\beta_4*familie+\epsilon\)</span></p>
<p><strong>h) Hvilken ansættelses-kategori er udeladt som referencekategori? Og hvilket køn?</strong></p>
<p><em>Kategorien “lønmodtager” er udeladt som referencekategori for ansættelsestype og kategorien “mand” er udeladt som referencekategori for køn.</em></p>
<p><strong>j) Estimér model 3</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>model3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(net_indkomst <span class="sc">~</span> kvinde <span class="sc">+</span> udd_aar <span class="sc">+</span> selvstaending <span class="sc">+</span> familie, <span class="at">data =</span> df)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>(texreg<span class="sc">::</span><span class="fu">screenreg</span>(<span class="fu">list</span>(model1, model2, model3), <span class="at">include.ci=</span>F))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
=======================================================
               Model 1       Model 2       Model 3     
-------------------------------------------------------
(Intercept)    16977.70 ***  11506.14 ***  11619.77 ***
                (328.66)      (649.18)      (652.22)   
kvinde         -1802.47 ***  -1926.81 ***  -1940.44 ***
                (474.28)      (457.02)      (459.26)   
udd_aar                        398.91 ***    396.31 ***
                               (41.32)       (41.31)   
selvstaending                               -983.83    
                                           (1100.27)   
familie                                    -7826.67 *  
                                           (3938.99)   
-------------------------------------------------------
R^2                0.01          0.08          0.09    
Adj. R^2           0.01          0.08          0.08    
Num. obs.       1187          1187          1187       
=======================================================
*** p &lt; 0.001; ** p &lt; 0.01; * p &lt; 0.05</code></pre>
</div>
</div>
<p><strong>k) Beskriv med ord, hvad fortolkningen af værdien på konstantleddet er nu</strong></p>
<p><em>Konstantleddet alpha / intercept er den forventede værdi på den afhængige variabel “indkomst”, når alle uafhængige variable er lig 0. Konstantleddet/intercept beskriver altså nu den forventede indkomst for en person, der har 0 på den uafhængige variabel “kvinde” OG den uafhængige variabel “antal års uddannelse” OG den uafhængige variabel “Selvstændig” OG den uafhængige variabel “Familie”.<br>
<br>
Med andre ord beskriver konstantleddet nu den forventede indkomst for mænd med 0 års uddannelse, som er lønmodtagere. “Lønmodtager” bliver nemlig referencekategorien for de to dummyvariable “selvstændig” og familie”, da det er den kategori på variablen “ansættelsestype”, der bliver ekskluderet fra modellen. Da de tre kategorier er gensidigt udelukkede, er man per definition lønmodtager, hvis man har 0 på dummyvariablen “selvstændig” og på dummyvariablen “familie”.</em></p>
<p><strong>l) Beskriv med ord, hvad fortolkningen af værdien på koefficienten for ansættelsestypen “Selvstændig” er:</strong></p>
<p><em>Parameterestimatet for dummy variablen “selvstændig” beskriver den forventede forskel/ændring i den afhængige variabel “indkomst”, mellem referencekategorien “lønmodtager” og kategorien “selvstændig”, når der kontrolleres for køn og antal års uddannelse. Selvstændige ser altså ud til gennemsnitligt at tjene 984 DKK mindre end lønmodtagere. Da der ikke er nogle stjerner på parameterestimatet er p-værdien &gt;= 0,05. Der ser altså ikke ud til at være en statistisk signifikant forskel på indkomsten mellem lønmodtagere og selvstændige, når der kontrolleres for køn og antal års uddannelse.</em></p>
<p><strong>m) Beskriv med ord, hvad fortolkningen af værdien på koefficienten for ansættelsestypen “Familie” er</strong></p>
<p><em>Parameterestimatet for dummy variablen “familie” beskriver den forventede forskel/ændring i den afhængige variabel “indkomst”, mellem referencekategorien “lønmodtager” og kategorien “familie”, når der kontrolleres for køn og antal års uddannelse. Den ene stjerne indikerer, at p-værdien &lt; 0,05. Der er altså faktisk en signifikant forskel i indkomst på folk, der er hjemmegående og lønmodtagere på trods at det lave (!) antal observationer i denne kategori. Folk der arbejder i familien ser altså ud til gennemsnitligt at tjene 7827 DKK mindre end lønmodtagere.</em> <em>Med andre ord er forskellene så systematiske, at vi med mindre en 5% risiko for type-I fejl kan sige, at forskellen kan genfindes i populationen.</em></p>
<p><strong>n) Er der fortsat en signifikant forskel mellem koen og indkomst, selv når der kontrolleres for antal aars uddannelse OG ansættelsestype? Skriv med ord.</strong></p>
<p><em>De tre stjerner for parameterestimatet for</em> <span class="math inline">\(\beta_1\)</span> indikerer, at <em>p-værdien tilhørende variablen “kvinde” er under 0,001. Dette er under vores kritiske grænse på 0,05 og vi kan konkludere at forskellen/sammenhængen er statistisk signifikant. Kvinder tjener gennemsnitligt 1940 DKK mindre om måneden end mænd, når der kontrolleres for antal års uddannelse og ansættelsestype.</em></p>
</section>
<section id="opgave-3-forklaringskraft" class="level3">
<h3 class="anchored" data-anchor-id="opgave-3-forklaringskraft">Opgave 3: forklaringskraft</h3>
<p>I har nu undersøgt sammenhængen mellem køn og indkomst via. forlæns modelsøgning. I har estimeret tre forskelige modeller:</p>
<p><em>Model 1: simpel model kun med afhængig og uafhængig variabel (indkomst og køn)</em></p>
<p><em>Model 2: multipel model med én kontrolvariabel (indkomst, køn og antal års uddannelse)</em></p>
<p><em>Model 3: multipel model med to kontrolvariable (indkomst, køn, antal års uddannelse og ansættelsestype).</em></p>
<p>I skal nu sammenligne de tre modeller for at afgøre, hvilken en der har den højeste forklaringskraft ved at sammenligne de tre modellers <span class="math inline">\(R^2\)</span> værdi.</p>
<p><br></p>
<p><strong>a) Skriv med ord, hvad</strong> <span class="math inline">\(R^2\)</span> <strong>værdien fortæller os</strong></p>
<p><span class="math inline">\(R^2\)</span> <em>værdien er et udtryk for, hvor meget af variationen i den afhængige variabel, de uafhængige variabler kan forklare. Der er altså et mål for, hvor god vores model er til at forklare variation/forskelle i vores afhængige variabel indkomst.</em></p>
<p><strong>b) Sammenlign dine modellers</strong> <span class="math inline">\(R^2\)</span> <strong>værdi. Hvilken model har den højeste forklaringskraft?</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>(texreg<span class="sc">::</span><span class="fu">screenreg</span>(<span class="fu">list</span>(model1, model2, model3), <span class="at">include.ci=</span>F))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
=======================================================
               Model 1       Model 2       Model 3     
-------------------------------------------------------
(Intercept)    16977.70 ***  11506.14 ***  11619.77 ***
                (328.66)      (649.18)      (652.22)   
kvinde         -1802.47 ***  -1926.81 ***  -1940.44 ***
                (474.28)      (457.02)      (459.26)   
udd_aar                        398.91 ***    396.31 ***
                               (41.32)       (41.31)   
selvstaending                               -983.83    
                                           (1100.27)   
familie                                    -7826.67 *  
                                           (3938.99)   
-------------------------------------------------------
R^2                0.01          0.08          0.09    
Adj. R^2           0.01          0.08          0.08    
Num. obs.       1187          1187          1187       
=======================================================
*** p &lt; 0.001; ** p &lt; 0.01; * p &lt; 0.05</code></pre>
</div>
</div>
<p><em>Model 3 ser ud til at have den højeste</em> <span class="math inline">\(R^2\)</span> <em>værdi og dermed forklaringskraft. Kigger man dog på</em> den justerede <span class="math inline">\(R^2\)</span> <em>værdi (Adj. R^2), som kun inkluderer forklaringskraften blandt de variable, der bidrager signifikant til modellen, så er forklaringskraften i model 2 og 3 ens.</em></p>
<p><strong>c) Skriv med ord, hvor stor en del af variationen i indkomst kan den bedste model forklare?</strong></p>
<p><em>Tilsammen kan alle variablene i model tre forklare 9 % af variationen i den afhængige variabel indkomst. Kigger man på den justerede</em> <span class="math inline">\(R^2\)</span> <em>værdi (Adj. R^2), så forklarer model 2 og 3 begge 8 % af variationen i den afhængige variabel indkomst.</em> <em>Det er altså ikke helt klart, om model 3 faktisk har en højere forklaringskraft end model 2.</em></p>
</section>
<section id="opgave-4-f-test-for-to-modeller" class="level3">
<h3 class="anchored" data-anchor-id="opgave-4-f-test-for-to-modeller">Opgave 4: F-test for to modeller</h3>
<p>Man kan sammenligne, hvilke modeller der er bedst, ved at sammenligne deres forklaringskraft. Men der skal en hypotesetest til at afgøre, om én model har en signifikant højere forklaringskraft end en anden.</p>
<p>Når man sammenligner to modellers forklaringskraft, hvor der er mere end ét parameterestimat til forskel – som her, hvor model 2 og 3 har både parameterestimatet for ansættelsestypen “familie” og ansættelsestypen “selvstændig” til forskel – skal man altid benytte F-testen. F-testen kan nemlig teste, om den forklaringskraft, som flere variable tilsammen tilføjer, er signifikant forskellig fra 0.</p>
<p><strong>a) Opstil hypoteserne for F-testen mellem model 2 og model 3 med ord:</strong><br>
<br>
<em>H0: forklaringskraften i model 3 er ikke signifikant højere end i model 2</em></p>
<p><em>H1: forklaringskraften i model 3 er signifikant højere end i model 2</em></p>
<p><strong>b) Kør en F-test mellem model 2 og model 3</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>f_test <span class="ot">&lt;-</span> <span class="fu">anova</span>(model2, model3)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>(f_test_summary <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Forskel i Frihedsgrader"</span> <span class="ot">=</span> f_test<span class="sc">$</span>Df[<span class="dv">2</span>],        <span class="co"># Forskel i frihedsgrader</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"F-statistik"</span> <span class="ot">=</span> f_test<span class="sc">$</span>F[<span class="dv">2</span>],                     <span class="co"># F-statistik</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"P-værdi"</span> <span class="ot">=</span> <span class="fu">sprintf</span>(<span class="st">"%.4f"</span>, f_test<span class="sc">$</span><span class="st">`</span><span class="at">Pr(&gt;F)</span><span class="st">`</span>[<span class="dv">2</span>]), <span class="co"># P-værdi med 4 decimaler</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">check.names =</span> <span class="cn">FALSE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Forskel i Frihedsgrader F-statistik P-værdi
1                       2    2.358291  0.0950</code></pre>
</div>
</div>
<p><strong>c) Konkludér på testen. Forklarer model 3 signifikant mere end model 2?</strong></p>
<p><em>Da vi får en p-værdi på 0,095 overskrider den vores grænse på 0,05. Vi kan altså ikke afvise nulhypotesen og konkludere, at model 3 forklarer signifikant mere end model 2. Dette giver mening, da forskellen på model 2 og model 3 kun var dummierne for ansættelsestype. Variablen “selvstændig” var insignifikant og variablen “familie” kun lige akkurat signifikant (en stjerne). Vi kan med denne F-test ikke konkludere, at ansættelsestype-dummierne tilsammen bidrager med nogen signifikant forklaringskraft til modellen, og de kan derfor i princippet udelades fra modellen.</em></p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>