/* This Proc Format program was automatically generated by Stat/Transfer ver.14.3.1163.0727 */

/* ENCODING CP1252 */



libname library 'XXX' ;

proc format library = library ;
   value V4F
      1 = 'Grønlandsk'  
      2 = 'Dansk' ;
   value V5F
      1 = 'Det er blevet meget sværere, at få pengene til at slå til'  
      2 = 'Det er blevet noget sværere, at få pengene til at slå til'  
      3 = 'Det er hverken blevet lettere eller sværere, at få pengene til at slå til'  
      4 = 'Det er blevet noget lettere, at få pengene til at slå til'  
      5 = 'Det er blevet meget lettere, at få pengene til at slå til'  
      6 = 'Ved ikke'  
     .A = 'Uoplyst' ;
   value V6F
      1 = 'Jeg tror, at min økonomi vil blive forbedret'  
      2 = 'Jeg tror, at min økomoni stort set vil forblive uændret'  
      3 = 'Jeg tror, at min økonomi vil blive forringet'  
     .A = 'Uoplyst' ;
   value V7F
      1 = 'Vi skulle have beholdt det danske'  
      2 = 'Det nye flag er bedst'  
      3 = 'Vi skulle have haft et helt tredie'  
      4 = 'Ved ikke'  
     .A = 'Uoplyst' ;
   value V8F
      1 = 'Samarbejde med inuit i Canada, Alaska og Sibrien bør gå forud for samarbejdet med de nordiske lande'  
      2 = 'Samarbejde med de nordiske lande bør gå forud for samarbejde med inuit i Canada, Alaska og Sibrien'  
      3 = 'Samarbejde med inuit i Canada, Alaska og Sibrien og samarbejde med de nordiske lande er lige vigtigt'  
      4 = 'Ved ikke'  
     .A = 'Uoplyst' ;
   value V9F
      1 = 'Jeg får ind for frit salg af øl, vin og spiritus'  
      2 = 'Jeg går ind for rationering under en eller form'  
      3 = 'Jeg går ind for totalforbud'  
      4 = 'Ved ikke'  
      5 = 'Andet'  
     .A = 'Uoplyst' ;
   value V10F
      1 = 'Atassut'  
      2 = 'Siumut'  
      3 = 'Inuit Ataqatigiit'  
      4 = 'Issittup Partiia'  
      5 = 'Ville stemme blankt'  
      6 = 'Ville ikke stemme'  
      7 = 'Ved ikke'  
      8 = 'Andet'  
     .A = 'Uoplyst' ;
   value V11F
      1 = 'Jeg støtter partiets grundlæggende ideer'  
      2 = 'Partiet varetager bedst mine interesser'  
      3 = 'Min familie og venner støtter partiet'  
      4 = 'Partiet har de dygtigste ledere'  
      5 = 'Partiet har den bedste politik på aktuelle politiske emner'  
      6 = 'Ved ikke'  
      7 = 'Andet'  
     .A = 'Uoplyst' ;
   value V12F
      1 = 'Atassut'  
      2 = 'Siumut'  
      3 = 'Inuit Ataqatigiit'  
      4 = 'Issittup Partiia'  
      5 = 'Ved ikke'  
     .A = 'Uoplyst' ;
   value V13F
      1 = 'Ja - gå til spm. 10 (V14) besvar ikke spm. 11 (V15)'  
      2 = 'Nej - gå til spm. 11 (V15)'  
      3 = 'Husker ikke - gå til spm. 12 (V16)'  
     .A = 'Uoplyst' ;
   value V14F
      1 = 'Atassut'  
      2 = 'Siumut'  
      3 = 'Inuit Ataqatigiit'  
      4 = 'Issittup Partiia'  
      5 = 'Kandidat udenfor partierne'  
      6 = 'Stemte blankt'  
      7 = 'Husker ikke'  
     .A = 'Uoplyst'  
     .B = 'Irrelevant' ;
   value V15F
      1 = 'Jeg var ikke fyldt 18'  
      2 = 'Det interesserede mig ikke'  
      3 = 'Jeg var syg'  
      4 = 'Jeg boede ikke i Grønland'  
      5 = 'Jeg havde boet her under 6 måneder'  
      6 = 'Ved ikke'  
      7 = 'Andet'  
     .A = 'Uoplyst'  
     .B = 'Irrelevant' ;
   value V16F
      1 = 'Ja - gå til spm. 13 (V17) besvar ikke spm. 14 (V18)'  
      2 = 'Nej - gå til spm. 14 (V18)'  
      3 = 'Husker ikke - gå til spm. 15 (V19)'  
     .A = 'Uoplyst' ;
   value V17F
      1 = 'Atassut'  
      2 = 'Siumut'  
      3 = 'Inuit Ataqatigiit'  
      4 = 'Issittup Partiia'  
      5 = 'Kandidat udenfor partierne'  
      6 = 'Stemte blankt'  
      7 = 'Husker ikke'  
     .A = 'Uoplyst'  
     .B = 'Irrelevant' ;
   value V18F
      1 = 'Jeg var ikke fyldt 18'  
      2 = 'Det interesserede mig ikke'  
      3 = 'Jeg var syg'  
      4 = 'Jeg boede ikke i Grønland'  
      5 = 'Jeg havde boet her under 6 måneder'  
      6 = 'Ved ikke'  
      7 = 'Andet'  
     .A = 'Uoplyst'  
     .B = 'Irrelevant' ;
   value V19F
      1 = 'a/s'  
      2 = 's/ia'  
      3 = 'a/ia'  
      4 = 'as/ia'  
      5 = 'as/ip'  
      6 = 'Alle'  
      7 = 'Ved ikke'  
     .A = 'Uoplyst' ;
   value V20F
      79 = '????'  
      92 = '????'  
     .A = 'Uoplyst' ;
   value V21F
      0 = 'Jm'  
      1 = 'Otto'  
      2 = 'Aqqa'  
      3 = 'Lej'  
      4 = 'Lc'  
      5 = 'Tuusi'  
      6 = 'Hpr'  
      7 = 'Ks'  
      8 = 'Nh'  
      10 = 'Ea'  
      11 = 'Jl'  
      12 = 'Hr'  
      14 = 'Mp'  
      15 = 'Andre'  
     .A = 'Uoplyst' ;
   value V22F
      1 = 'Ja'  
      2 = 'Nej'  
      3 = 'Husker ikke'  
     .A = 'Uoplyst' ;
   value V23F
      1 = 'Ja'  
      2 = 'Nej'  
      3 = 'Husker ikke'  
     .A = 'Uoplyst' ;
   value V24F
      1 = 'Ja'  
      2 = 'Nej'  
      3 = 'Husker ikke'  
     .A = 'Uoplyst' ;
   value V25F
      1 = 'Ja'  
      2 = 'Nej'  
      3 = 'Husker ikke'  
     .A = 'Uoplyst' ;
   value V26F
      1 = 'Ja'  
      2 = 'Nej'  
      3 = 'Husker ikke'  
     .A = 'Uoplyst' ;
   value V27F
      1 = 'Ja'  
      2 = 'Nej'  
      3 = 'Husker ikke'  
     .A = 'Uoplyst' ;
   value V28F
      1 = 'Ja'  
      2 = 'Nej'  
      3 = 'Husker ikke'  
     .A = 'Uoplyst' ;
   value V29F
      1 = 'Ja'  
      2 = 'Nej'  
      3 = 'Husker ikke'  
     .A = 'Uoplyst' ;
   value V30F
      1 = 'Ja'  
      2 = 'Nej'  
      3 = 'Husker ikke'  
     .A = 'Uoplyst' ;
   value V31F
      1 = 'Enig med A'  
      2 = 'Enig med B'  
      3 = 'Ved ikke'  
     .A = 'Uoplyst' ;
   value V32F
      1 = 'Enig med A'  
      2 = 'Enig med B'  
      3 = 'Ved ikke'  
     .A = 'Uoplyst' ;
   value V33F
      1 = 'Enig med A'  
      2 = 'Enig med B'  
      3 = 'Ved ikke'  
     .A = 'Uoplyst' ;
   value V34F
      1 = 'Enig med A'  
      2 = 'Enig med B'  
      3 = 'Ved ikke'  
     .A = 'Uoplyst' ;
   value V35F
      1 = 'Enig med A'  
      2 = 'Enig med B'  
      3 = 'Ved ikke'  
     .A = 'Uoplyst' ;
   value V36F
      1 = 'Enig med A'  
      2 = 'Enig med B'  
      3 = 'Ved ikke'  
     .A = 'Uoplyst' ;
   value V37F
      1 = 'Enig med A'  
      2 = 'Enig med B'  
      3 = 'Ved ikke'  
     .A = 'Uoplyst' ;
   value V38F
      1 = 'De amerikanske baser kan og skal lukkes med det samme, også selv om Hjemmestyret skal bekoste den fortsatte drift af lu'  
      2 = 'De amerikanske baser skal lukkes så snart, der findes en økonomisk forsvarlig måde, at drive lufthavnene videre på'  
      3 = 'De amerkanske baser skal ikke afvikles før spændingen i verden er blevet mindre'  
      4 = 'Det vil altid være en fordel for Grønland, at have amerikanske baser i landet'  
      5 = 'Ved ikke'  
     .A = 'Uoplyst' ;
   value V39F
      1 = 'Jeg syntes, at de har klaret dem godt'  
      2 = 'Jeg syntes, at de har klaret dem nogenlunde godt'  
      3 = 'Jeg syntes ikke, at de har klaret dem særlig godt'  
      4 = 'Jeg syntes, at de har klaret dem dårligt'  
      5 = 'Ved ikke'  
     .A = 'Uoplyst' ;
   value V40F
      1 = 'Mand'  
      2 = 'Kvinde'  
     .A = 'Uoplyst' ;
   value V41F
     .A = 'Uoplyst' ;
   value V42F
      1 = '18 - 19 år'  
      2 = '20 - 29 år'  
      3 = '30 - 39 år'  
      4 = '40 - 49 år'  
      5 = '50 - 59 år'  
      6 = '60 - 69 år'  
      7 = 'Over 70 år'  
     .A = 'Uoplyst' ;
   value V43F
      1 = 'By'  
      2 = 'Bygd'  
      3 = 'Base'  
     .A = 'Uoplyst' ;
   value V44F
      0 = 'Ta + Sc'  
      1 = 'Nan'  
      2 = 'Qaq'  
      3 = 'Nar'  
      4 = 'Ivit'  
      5 = 'Paa'  
      6 = 'Nu + Uk'  
      7 = 'Man'  
      8 = 'Sis'  
      9 = 'Kang'  
      10 = 'Aas'  
      11 = 'Qa + Qe'  
      12 = 'Ilul'  
      13 = 'Uumm'  
      14 = 'Uper'  
      15 = 'Qaan' ;
   value V45F
      1 = 'Ja - gå til spm. 40 (V46)'  
      2 = 'Nej - gå til spm. 41 (V47)'  
      4 = 'Fejlkode - gå til spm. 41 (V47)'  
      5 = 'Fejlkode - gå til spm. 41 (V47)'  
      6 = 'Fejlkode - gå til spm. 41 (V47)'  
      7 = 'Fejlkode - gå til spm. 41 (V47)'  
     .A = 'Uoplyst' ;
   value V46F
      1 = 'Et andet sted i Grønland'  
      2 = 'Danmark'  
      3 = 'Et sted udenfor Grønland og Danmark'  
     .A = 'Uoplyst'  
     .B = 'Irrelevant' ;
   value V47F
      1 = 'Grønland'  
      2 = 'Danmark'  
      3 = 'Andet land'  
     .A = 'Uoplyst' ;
   value V48F
      1 = 'Gift/samlevende - gå til spm. 43 (V49)'  
      2 = 'Enlig - gå til spm. 44 (V50)'  
     .A = 'Uoplyst' ;
   value V49F
      1 = 'Grønland'  
      2 = 'Danmark'  
      3 = 'Andet land'  
     .A = 'Uoplyst'  
     .B = 'Irrelevant' ;
   value V50F
      1 = 'Ja'  
      2 = 'Nej'  
     .A = 'Uoplyst' ;
   value V51F
      1 = 'Ja - gå til spm. 48 (V54)'  
      2 = 'Nej - gå til spm. 46 (V52) besvar ikke spm. 47 (V53)'  
      3 = 'Ved ikke - gå til spm. 47 (V53)'  
     .A = 'Uoplyst' ;
   value V52F
      1 = 'Flytter permanent fra Grønland'  
      2 = 'Flytter midlertidigt fra Grønland'  
     .A = 'Uoplyst'  
     .B = 'Irrelevant' ;
   value V53F
      1 = 'Overvejer at flytte permanent fra Grønland'  
      2 = 'Overvejer at flytte midlertidigt fra Grønland'  
     .A = 'Uoplyst'  
     .B = 'Irrelevant' ;
   value V54F
      0 = 'Mere end 9 personer'  
      1 = '1 person'  
      2 = '2 personer'  
      3 = '3 personer'  
      4 = '4 personer'  
      5 = '5 personer'  
      6 = '6 personer'  
      7 = '7 personer'  
      8 = '8 personer'  
     .A = 'Uoplyst' ;
   value V55F
      0 = 'Mere end 9 personer'  
      1 = '1 person'  
      2 = '2 personer'  
      3 = '3 personer'  
      4 = '4 personer'  
      5 = '5 personer'  
      6 = '6 personer'  
      7 = '7 personer'  
      8 = '8 personer'  
     .A = 'Uoplyst' ;
   value V56F
      1 = 'Ar.uf'  
      2 = 'Ar-fa'  
      3 = 'Fu-la'  
      4 = 'Fu-ho'  
      5 = 'Se-pr'  
      6 = 'Se-se'  
     .A = 'Uoplyst' ;
   value V57F
      1 = 'Prod'  
      2 = 'Ha + se'  
      3 = 'Of.ad'  
      4 = 'S + k + k'  
      5 = 'Su + po'  
      6 = 'So + in'  
     .A = 'Uoplyst' ;
   value V58F
      0 = 'Privat ansat'  
      1 = 'Offentlig ansat'  
      2 = 'Selvstændig'  
      3 = 'Hjemmegående husmor'  
      4 = 'Studerende/ lærling'  
      5 = 'Arbejdsløs'  
      6 = 'Pensioneret'  
      7 = 'Fangerkone/ medhjælpende ægtefælle'  
      8 = 'Ved ikke'  
     .A = 'Uoplyst' ;
   value V59F
     .A = 'Uoplyst'  
     .B = 'Irrelevant' ;
   value V60F
      0 = 'Privat ansat'  
      1 = 'Offentlig ansat'  
      2 = 'Selvstændig'  
      3 = 'Hjemmegående husmor'  
      4 = 'Studerende/lærling'  
      5 = 'Arbejdsløs'  
      6 = 'Pensioneret'  
      7 = 'Fangerkone/medhjælpende ægtefælle'  
      8 = 'Ved ikke'  
     .A = 'Uoplyst'  
     .B = 'Irrelevant' ;
   value V61F
      1 = 'Ingen'  
      2 = 'Under uddannelse'  
      3 = 'Kort'  
      4 = 'L/efg'  
      5 = 'K/boglig'  
      6 = 'L/boglig'  
     .A = 'Uoplyst' ;
   value V62F
      0 = '0 - 49.999 kr.'  
      1 = '50.000 - 99.999 kr.'  
      2 = '100.000 - 149.999 kr.'  
      3 = '150.000 - 199.999 kr.'  
      4 = '200.000 - 299.999 kr.'  
      5 = '300.000 - 399.999 kr.'  
      6 = '400.000 - 499.999 kr.'  
      7 = 'Over 500.000 kr.'  
      8 = 'Ved ikke'  
     .A = 'Uoplyst' ;
   value V63F
      0 = '0 - 49.999 kr.'  
      1 = '50.000 - 99.999 kr.'  
      2 = '100.000 - 149.999 kr.'  
      3 = '150.000 - 199.999 kr.'  
      4 = '200.000 - 299.999 kr.'  
      5 = '300.000 - 399.999 kr.'  
      6 = '400.000 - 499.999 kr.'  
      7 = 'Over 500.000 kr.'  
      8 = 'Ved ikke'  
     .A = 'Uoplyst' ;
   value V64F
      1 = 'Jeg har grønlandsk som hovedsprog og forstår og taler kun lidt dansk'  
      2 = 'Jeg har grønlandsk som hovedsprog og forstår og taler godt dansk'  
      3 = 'Jeg er dobbeltsproget'  
      4 = 'Jeg har dansk som hovedsprog og forstår og taler godt grønlandsk'  
      5 = 'Jeg har dansk som hovedsprog og forstår og taler godt kun lidt grønlandsk'  
      6 = 'Jeg har hverken dansk eller grønlandsk som hovedsprog'  
      7 = 'Ved ikke'  
     .A = 'Uoplyst' ;
   value V65F
      1 = 'Mest knyttet til den grønlandske befolkningsgruppe'  
      2 = 'Mest knyttet til den danske befolkningsgruppe'  
      3 = 'Lige meget knyttet til begge befolkningsgrupper'  
      4 = 'Ved ikke'  
     .A = 'Uoplyst' ;
   value V66F
      0 = '18 - 19 år'  
      1 = '20 - 24 år'  
      2 = '25 - 29 år'  
      3 = '30 - 34 år'  
      4 = '35 - 39 år'  
      5 = '40 - 44 år'  
      6 = '45 - 49 år'  
      7 = '50 - 59 år'  
      8 = 'Over 60 år'  
     .A = 'Uoplyst' ;
   value V67F
      1 = '0 - 100.000 kr'  
      2 = 'Under 200.000 kr'  
      3 = 'Over 200.000 kr'  
      4 = 'Ved ikke'  
     .A = 'Uoplyst' ;
   value V68F
      1 = '0 - 150.000 kr'  
      2 = 'Under 300.000 kr'  
      3 = 'Over 300.000 kr'  
      4 = 'Ved ikke'  
     .A = 'Uoplyst' ;
   value V69F
      1 = 'Nan'  
      2 = 'Qaq'  
      3 = 'Nar'  
      4 = 'Ivi'  
      5 = 'Paa'  
     .A = 'Uoplyst' ;
   value V70F
      1 = 'Nu + Uk'  
      2 = 'man'  
      3 = 'Sis'  
     .A = 'Uoplyst' ;
   value V71F
      1 = 'Kan'  
      2 = 'Aas'  
      3 = 'Qas'  
      4 = 'Ilu'  
      5 = 'Qeq'  
     .A = 'Uoplyst' ;
   value V72F
      1 = 'Uum'  
      2 = 'Uper'  
      3 = 'Aver'  
      4 = 'Tasi'  
      5 = 'Illo'  
     .A = 'Uoplyst' ;

proc datasets library = library ;
modify Data1518;
   format        V4 V4F.;
   format        V5 V5F.;
   format        V6 V6F.;
   format        V7 V7F.;
   format        V8 V8F.;
   format        V9 V9F.;
   format       V10 V10F.;
   format       V11 V11F.;
   format       V12 V12F.;
   format       V13 V13F.;
   format       V14 V14F.;
   format       V15 V15F.;
   format       V16 V16F.;
   format       V17 V17F.;
   format       V18 V18F.;
   format       V19 V19F.;
   format       V20 V20F.;
   format       V21 V21F.;
   format       V22 V22F.;
   format       V23 V23F.;
   format       V24 V24F.;
   format       V25 V25F.;
   format       V26 V26F.;
   format       V27 V27F.;
   format       V28 V28F.;
   format       V29 V29F.;
   format       V30 V30F.;
   format       V31 V31F.;
   format       V32 V32F.;
   format       V33 V33F.;
   format       V34 V34F.;
   format       V35 V35F.;
   format       V36 V36F.;
   format       V37 V37F.;
   format       V38 V38F.;
   format       V39 V39F.;
   format       V40 V40F.;
   format       V42 V42F.;
   format       V43 V43F.;
   format       V44 V44F.;
   format       V45 V45F.;
   format       V46 V46F.;
   format       V47 V47F.;
   format       V48 V48F.;
   format       V49 V49F.;
   format       V50 V50F.;
   format       V51 V51F.;
   format       V52 V52F.;
   format       V53 V53F.;
   format       V54 V54F.;
   format       V55 V55F.;
   format       V56 V56F.;
   format       V57 V57F.;
   format       V58 V58F.;
   format       V60 V60F.;
   format       V61 V61F.;
   format       V62 V62F.;
   format       V63 V63F.;
   format       V64 V64F.;
   format       V65 V65F.;
   format       V66 V66F.;
   format       V67 V67F.;
   format       V68 V68F.;
   format       V69 V69F.;
   format       V70 V70F.;
   format       V71 V71F.;
   format       V72 V72F.;
quit;
